### ISSUE TITLE
Postload

### ISSUE THREAD

**Issue by jmatsushita** [redhat-developer/devfile#33]
Hi there,

I'm trying to run a post startup macro in che, in order to reconfigure multiple containers with the route urls assigned by https://che.openshift.io (`7.0.0-RC-1.1`)

In order to avoid user intervention I was hoping to use something like [`Chefile`](https://www.eclipse.org/che/docs/che-6/chefile.html)'s `workspace.postload.actions[1].script`. Is this something that could be part of `devfile`s ? Or is there another approach to launching commands after the workspace is loaded? IIUC this is the only moment in the lifecycle of a workspace where route urls will be available. Should this be more of a che upstream issue?

Thanks,

Jun

**Comment by sunix** [comment]
yes if you could create an issue in https://github.com/eclipse/che/issues/new/choose 
thanks
