### ISSUE TITLE
Update Devfile diagrams 

### ISSUE THREAD

**Issue by sleshchenko** [redhat-developer/devfile#8]
This repository contains diagrams that are outdated, like `DevelopmentTool` has `attributes` and `version` which are not supported and AFAIK there are no plans to support it (at least `version`), or `mountProjectsSources` is dockerimage tool specific field and correct field name is `mountSources`.
It is needed to make diagrams up to date.

**Comment by sleshchenko** [comment]
@l0rd Do you think we still need these diagrams or they should be dropped?

cc @skabashnyuk

**Comment by l0rd** [comment]
I think these diagrams are good documentation. We should updated them in the context of https://github.com/eclipse/che/issues/12732. 

`mountProjectsSources` and `version` make sense for any type `DevelopmentTool`. We will need to implement it.

**Comment by skabashnyuk** [comment]
СС @mshaposhnik

**Comment by mshaposhnik** [comment]
Done in https://github.com/redhat-developer/devfile/pull/18
